config/routes.rb
Dating::Application.routes.draw do
  get "messages/index"
  devise_for :users

  root 'welcome#index', as: :home

  get 'profiles' => 'profiles#index'
  patch 'profile' => 'profiles#update', as: :update_profile
  get 'profile/edit' => 'profiles#edit', as: :edit_profile
  get 'p/:username' => 'profiles#show', as: :profile
  post 'p/:username' => 'profiles#create_share', as: :shares

  get 'images/new' => 'images#new', as: :new_image
  get 'i/:username' => 'images#index', as: :images
  get 'i/:username/:id', to: 'images#show', as: :image
  post 'images/create' => 'images#create', as: :create_image
  delete 'images/destroy', to: 'images#destroy', as: :destroy_image
  put 'images/avatar' => 'images#avatar'

  post 'comments/create', to: 'comments#create', as: :create_comment

  get 'messages/:username', to: 'messages#index', as: :messages
  post 'messages', to: 'messages#create', as: :create_message

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :sender, :class_name => "User"
  belongs_to :receiver, :class_name => "User"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index

    if !user_signed_in?
      redirect_to :root
    end

    @conversations = current_user.conversations
    @receiver = User.find_by_username(params[:username])
    set_conversation(@receiver.id)
  end

    #responds to AJAX post request
    def create
      if (user_signed_in?)
        message = current_user.messages.new(message_params)
        message.receiver = User.find(params[:message][:receiver_id])
        set_conversation(message.receiver.id)
        message.sender = current_user
        message.conversation = @conversation
        if message.save
          render :partial => 'messages/message.html', :locals =>{:message => message}
        end
      end
    end

    def message_params
      params.require(:message).permit(:content, :receiver_id)
    end

    private

    def set_conversation(receiver_id)
      @conversation = Conversation.where(
        '(sender_id = ? AND receiver_id = ?) OR (receiver_id =? AND sender_id = ?)',
        receiver_id, current_user.id, receiver_id, current_user.id)
      .order(id: :desc).first

      if @conversation.nil?
        @conversation = Conversation.create(sender_id: current_user.id, receiver_id: receiver_id)
      end
    end
  end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_conversation.html.erb
<li>
  <div class="media innerAll half conversation_boxie">
    <div class="media-object pull-left thumb hidden-phone"><img data-src="holder.js/50x50/dark" alt="Image" /></div>
    <div class="media-body">
      <span class="strong"><a href="<%= messages_path conversation.other_user(current_user).username %>"><%= conversation.other_user(current_user).username %></a></span>
      <small>Latest comment line...</small><br/>
      <small class="text-italic text-primary-light"><i class="fa fa-calendar fa fa-fixed-width"></i> 17 days ago</small>
    </div>
  </div>
  <script type="text/javascript">
$(".conversation_boxie").click(function(){
     window.location=$(this).find("a").attr("href");
     return false;
});
  </script>
</li>

app/views/messages/_form.html.erb
<form role="form" action="<%= create_message_path %>" method="post" id="new_message_form">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <input type="hidden" value="<%=@receiver.id%>" name="message[receiver_id]" />

  <div class="form-group">
    <textarea placeholder="Type in your message .. " class="form-control col-md-12" rows="5" name="message[content]" id="message_content" ></textarea>
  </div>
  <div class="form-group">
    <div class="text-right ">
      <button type="submit" class="btn btn-primary">Send <i class="innerL half fa fa-envelope"></i></button>
    </div>
  </div>
</form>

<%= render 'messages/form_js'%>

app/views/messages/_form_js.html.erb
<script type="text/javascript">
  function scrollWinwdow(){
    $('#messages_list').scrollTop($('#messages_list').prop("scrollHeight"));
    return false;
  }

  $(document).ready(function() {
    $("#new_message_form").submit(function() {


      if ($('#message_content').val() == "") {
        alert("Please enter a message first!");
        return false;
      }
      form_data = $(this).serialize();
      $.ajax({
        type: "POST",
        url: '<%= create_message_path %>',
        data: form_data,
        dataType: 'html', //important
        success: function(data) {
          $("#messages_list").append(data);
          $('#message_content').val('');
          scrollWinwdow();
        },
        error: function(jqXHR, textStatus, errorThrown) {
          // console.log(jqXHR);
          // console.log(textStatus);
          // console.log(errorThrown);
        }
      });

      return false;
    });
  });

  $(window).load( scrollWinwdow());




</script>

app/views/messages/_message.html.erb
<div class="row row-merge borders border-top">
  <div class="col-md-12">
    <div class="innerAll half">
      <div class="media">
        <a href="<%= profile_path message.sender.username %>" class="thumb pull-left visible-md visible-lg"><%= image_thumb message.sender.avatar, ' class="media-object" style="width: 50px; height: 50px" '%></a>
        <div class="media-body">
          <small class="pull-right text-primary-light"><i class="fa fa-calendar fa fa-fixed-width"></i> <%= distance_of_time_in_words_to_now(message.created_at) %> ago</small>
          <strong class="text-primary"><%= message.sender.username %></strong><br/>
          <small><%= message.content -%></small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<!-- Widget -->
<div class="widget widget-messages widget-heading-simple widget-body-white">
  <div class="widget-body padding-none">

    <div class="row row-merge borders">
      <div class="col-md-3 listWrapper">
        <div class="innerAll">
          <form autocomplete="off" class="form-inline margin-none">
            <div class="input-group input-group-sm">
              <input type="text" class="form-control" placeholder="Find someone .." />
              <span class="input-group-btn">
                <button type="button" class="btn btn-primary btn-xs pull-right"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
        </div>
        <span class="results">1490 messages <i class="fa fa-circle-arrow-down"></i></span>
        <ul class="list unstyled">
          <% @conversations.each do |conversation| %>
            <%= render 'conversation', :conversation => conversation %>
          <% end %>
        </ul>
      </div>
      <div class="col-md-9 detailsWrapper" >
        <div class="ajax-loading hide">
          <i class="fa fa-refresh text-primary-light fa fa-spin fa fa-4x"></i>
        </div>
        <div class="innerAll half">
          <div class="row margin-none">
            <div class="col-md-9">
              <h4 class="margin-none">
                <a href="" class="btn btn-info"><i class="fa fa-user fa fa-fixed-width"></i>
                  <%=@receiver.username %></a>
                </h4>
              </div>
              <div class="col-md-3 text-right">
                <a href="" class="text-size-regular text-primary-light vertical-middle"><i class="fa fa-flag fa fa-fixed-width"></i> Report</a>
              </div>
            </div>
          </div>
          <a href="" class="load border-top ">Load earlier messages <i class="fa fa-refresh innerL third"></i></a>
          <div style=" overflow-y: scroll; height: 350px;" id="messages_list">
            <% @conversation.messages.each do |message| %>
            <%= render 'message', :message => message %>
            <% end %>
          </div>

          <span href="" class="load"><i class="fa fa-calendar innerR third"></i>Today</span>



          <div class="innerAll" id="insert_new_message_above" style="">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- // Widget END -->


  <script src="<%= asset_url 'components/modules/admin/messages/assets/js/messages.js' %>"></script>
  <script src="<%= asset_url 'components/plugins/holder/holder.js' %>"></script>