config/routes.rb
Dating::Application.routes.draw do
  get "messages/index"
  devise_for :users

  root 'welcome#index', as: :home

  get 'profiles' => 'profiles#index'
  patch 'profile' => 'profiles#update', as: :update_profile
  get 'profile/edit' => 'profiles#edit', as: :edit_profile
  get 'p/:username' => 'profiles#show', as: :profile
  post 'p/:username' => 'profiles#create_share', as: :shares

  get 'images/new' => 'images#new', as: :new_image
  get 'i/:username' => 'images#index', as: :images
  get 'i/:username/:id', to: 'images#show', as: :image
  post 'images/create' => 'images#create', as: :create_image
  delete 'images/destroy', to: 'images#destroy', as: :destroy_image
  put 'images/avatar' => 'images#avatar'

  post 'comments/create', to: 'comments#create', as: :create_comment

  get 'messages/:username', to: 'messages#index', as: :messages
  post 'messages', to: 'messages#create', as: :create_message

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    results_per_page = 10
    if params[:search]

      search_params = {:birthday => (params[:search][:age_max].to_i+1).years.ago.to_date..params[:search][:age_min].to_i.years.ago.to_date}

      if !params[:search][:city_id].empty?
        search_params[:city_id] = params[:search][:city_id]
      end
      if !params[:search][:sex].empty?
        search_params[:sex] = params[:search][:sex]
      end

      @profiles = User.where(search_params).paginate(page: params[:page], per_page: results_per_page)
    else
      @profiles = User.all.paginate(page: params[:page], per_page: results_per_page)
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to edit_profile_path, flash: { success: t('Successfully updated.')}
    else
      render action: 'edit'
    end
  end


  def show
    @user = User.find_by_username(params[:username]) || not_found
    @share ||= Share.new
    @shares = @user.shares_on_profile.all(:order => "id DESC")
    render 'show'
  end

  def create_share
    @share = current_user.shares_authored.new(share_params)
    @share.user_id = params[:share][:user_id]
    saved = @share.save
    if saved == true
      flash[:notice] = 'message'
      @share = Share.new
    end

    if saved == false
      show
      return
    else
      redirect_to  :action => 'show', :username =>params[:share][:username]
    end
  end

  private
  def share_params
    params.require(:share).permit(:content)
  end

  def user_params
    params.require(:user).permit( :birthday, :city_id, :sex, :height, :weight, :pets,
     :hobbies, :sports, :movies, :music, :books, :likes, :dislikes, :eye_color  )
  end

end

app/views/profiles/_form.html.erb
<%= simple_form_for @user, :url => update_profile_path, :class => 'form-horizontal' do |f| %>

<%= render 'shared/error_messages', object: f.object %>



    <div class="form-group margin-none innerB">
      <%= f.label :birthday, class: 'col-md-3 control-label' %>
      <div class="col-md-9">
        <div class="input-group">
          <%= f.input_field :birthday, :class => 'form-control pull-left',
          :style => 'width: auto !important;',
           as: :date, start_year: Date.today.year - 90,
          end_year: Date.today.year - 12, order: [:day, :month, :year] %>

        </div>
      </div>
    </div>



<%= f.association :city, collection: City.all( order: 'name'), include_blank: false %>

<%= f.input :sex, include_blank: false %>

<%= f.input :height, collection: (100..220),  include_blank: false  %>

<%= f.input :weight, collection: (40..250),  include_blank: false  %>

<%= f.input :pets %>

<%= f.input :eye_color, include_blank: false %>

<%= f.input :hobbies %>
<%= f.input :sports %>
<%= f.input :movies %>
<%= f.input :music %>
<%= f.input :books %>
<%= f.input :likes %>
<%= f.input :dislikes %>

<%= f.button :submit %>
<% end %>

app/views/profiles/_middle_col.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="widget activity-line">
      <div class="widget-body padding-none">
        <div class="share" >

          <%= simple_form_for(@share, :url => :shares,
          :html => {:style => ' height: 123px; '}) do |f| %>

          <%= render 'shared/error_messages', object: f.object %>

          <%=f.text_area(:content,:cols =>53, :rows => 4)%>
          <%=f.hidden_field(:user_id, value: @user.id)  %>
          <%=f.hidden_field(:username, value: @user.username)  %>

          <%=f.button(:submit, :class=>'btn btn-primary  btn-sm pull-right') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <%= render 'profiles/tabs/photos', :user => @user %>
  </div>
</div>
<div class="row">

  <% @shares.each do |share| %>
  <%= render 'profiles/tabs/share', :share => share %>
  <% end %>

</div>

app/views/profiles/_right_col.html.erb
asdasdasda sdasd asd asd sa dsa

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/index.html.erb
<div class="col-md-12">

    <!-- col-separator -->
    <div class="col-separator col-separator-first border-none">

      <!-- col-table -->
      <div class="col-table">

        <!-- col-table-row -->
        <div class="col-table-row">

          <!-- col-app -->
          <div class="col-app">

            <!-- row-app -->
            <div class="row row-app margin-none">

              <%= render 'profiles/index/left_col' %>

              <%= render 'profiles/index/right_col' %>


            </div>
            <!-- // END row -->

          </div>
          <!-- // END col-app -->

        </div>
        <!-- // END col-table-row -->

      </div>
      <!-- // END col-table -->

    </div>
    <!-- // END col-separator -->

  </div>

app/views/profiles/show.html.erb
<div class="col-md-2">
  <%= render 'shared/profile_left_col' %>
</div>
<div class="col-md-8">
  <%= render 'profiles/middle_col' %>
</div>
<div class="col-md-2">
  <%= render 'profiles/right_col' %>
</div>