config/routes.rb
Dating::Application.routes.draw do
  get "messages/index"
  devise_for :users

  root 'welcome#index', as: :home

  get 'profiles' => 'profiles#index'
  patch 'profile' => 'profiles#update', as: :update_profile
  get 'profile/edit' => 'profiles#edit', as: :edit_profile
  get 'p/:username' => 'profiles#show', as: :profile
  post 'p/:username' => 'profiles#create_share', as: :shares

  get 'images/new' => 'images#new', as: :new_image
  get 'i/:username' => 'images#index', as: :images
  get 'i/:username/:id', to: 'images#show', as: :image
  post 'images/create' => 'images#create', as: :create_image
  delete 'images/destroy', to: 'images#destroy', as: :destroy_image
  put 'images/avatar' => 'images#avatar'

  post 'comments/create', to: 'comments#create', as: :create_comment

  get 'messages/:username', to: 'messages#index', as: :messages
  post 'messages', to: 'messages#create', as: :create_message

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

  <div class="alert alert-primary">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    The form contains <%= pluralize(object.errors.count, "error") %>.

    <div>
      <% object.errors.full_messages.each do |msg| %>
        - <%= msg %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| -%>
<% #*name = success/info/primary/warning %>
<!-- Alert -->
<div class="alert alert-<%=name%>">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= msg%>
</div>
<!-- // Alert END -->
<% end -%>

app/views/shared/_profile_left_col.html.erb
<div class="col-separator box col-separator-first reset-components hasNiceScroll" style="overflow-y: hidden; outline: none;" tabindex="5000">
  <div class="bg-white">
    <div class="profile-avatar">
      <div class="text-center">
      <% if !@user.avatar.nil? %>
       <%= link_to(image_medium(@user.avatar, ' class="img-responsive img-clean" '),
        image_path(username: @user.username, id: @user.avatar.id)) %>
        <% else %>
 <%= image_medium(@user.avatar, ' class="img-responsive img-clean" ') %>
        <% end %>
      </div>
    </div>

    <div class="innerAll">
      <h4><i class="fa fa-circle text-success pull-right"></i> <%= @user.username  %> </h4>
      <p class="margin-none text-muted"><%= "#{@user.age} / #{@user.sex_text} / #{@user.city.name}"%></p>
    </div>


  </div>
  <div class="col-separator-h box"></div>

  <ul class="list-group list-group-1 margin-none">
    <% if user_signed_in? && current_user.id == @user.id %>
    <li class="list-group-item border-top-none active">
    <a href="<%= new_image_path %>"><i class="fa fa-book"></i> Upload photo</a>
    </li>
    <% end %>

    <li class="list-group-item border-top-none active">
      <a href="<%= url_for controller: :profiles, action: :show, username: @user.username %>"><i class="fa fa-book"></i> Profile</a>
    </li>
    <li class="list-group-item">
      <span class="badge pull-right badge-primary hidden-md"><%= @user.images.count %></span>
      <a href="<%= url_for controller: :images, action: :index, username: @user.username %>"><i class="fa fa-camera"></i> Photos</a>
    </li>

  </ul>


  <div class="col-separator-h box"></div>




  <div class="col-separator-h box"></div>

</div>