config/routes.rb
Dating::Application.routes.draw do
  get "messages/index"
  devise_for :users

  root 'welcome#index', as: :home

  get 'profiles' => 'profiles#index'
  patch 'profile' => 'profiles#update', as: :update_profile
  get 'profile/edit' => 'profiles#edit', as: :edit_profile
  get 'p/:username' => 'profiles#show', as: :profile
  post 'p/:username' => 'profiles#create_share', as: :shares

  get 'images/new' => 'images#new', as: :new_image
  get 'i/:username' => 'images#index', as: :images
  get 'i/:username/:id', to: 'images#show', as: :image
  post 'images/create' => 'images#create', as: :create_image
  delete 'images/destroy', to: 'images#destroy', as: :destroy_image
  put 'images/avatar' => 'images#avatar'

  post 'comments/create', to: 'comments#create', as: :create_comment

  get 'messages/:username', to: 'messages#index', as: :messages
  post 'messages', to: 'messages#create', as: :create_message

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    results_per_page = 10
    if params[:search]

      search_params = {:birthday => (params[:search][:age_max].to_i+1).years.ago.to_date..params[:search][:age_min].to_i.years.ago.to_date}

      if !params[:search][:city_id].empty?
        search_params[:city_id] = params[:search][:city_id]
      end
      if !params[:search][:sex].empty?
        search_params[:sex] = params[:search][:sex]
      end

      @profiles = User.where(search_params).paginate(page: params[:page], per_page: results_per_page)
    else
      @profiles = User.all.paginate(page: params[:page], per_page: results_per_page)
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to edit_profile_path, flash: { success: t('Successfully updated.')}
    else
      render action: 'edit'
    end
  end


  def show
    @user = User.find_by_username(params[:username]) || not_found
    @share ||= Share.new
    @shares = @user.shares_on_profile.all(:order => "id DESC")
    render 'show'
  end

  def create_share
    @share = current_user.shares_authored.new(share_params)
    @share.user_id = params[:share][:user_id]
    saved = @share.save
    if saved == true
      flash[:notice] = 'message'
      @share = Share.new
    end

    if saved == false
      show
      return
    else
      redirect_to  :action => 'show', :username =>params[:share][:username]
    end
  end

  private
  def share_params
    params.require(:share).permit(:content)
  end

  def user_params
    params.require(:user).permit( :birthday, :city_id, :sex, :height, :weight, :pets,
     :hobbies, :sports, :movies, :music, :books, :likes, :dislikes, :eye_color  )
  end

end

app/views/profiles/index/_left_col.html.erb
<div class="col-sm-12 col-md-2 col-lg-2">
  <!-- col-separator -->
  <div class="col-separator hasNiceScroll" style="overflow-y: hidden; outline: none;" tabindex="5000">

   <%= form_tag profiles_path, :method => 'get' do %>
   <div class="widget-body padding-none">

    <div class="innerAll border-bottom">


      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-map-marker"></i>
        </span>

        <%= select_tag "search[city_id]",
        options_from_collection_for_select(City.all, 'id', 'name', params[:search].nil? ? nil : params[:search][:city_id]), :include_blank => true,
        :class=>'form-control' %>

      </div>
    </div>

    <div class="innerAll border-bottom text-center" >
      <%= select_tag 'search[sex]', options_for_select(User.sex.options, params[:search].nil? ?  current_user.opposite_sex : params[:search][:sex]),
      :class => 'form-control'       %>

    </div>


    <div class="innerAll border-bottom text-center" >
      <div class="row">
        <div class="col-md-6">
        From
        <%= select_tag 'search[age_min]' , options_for_select((14..100), params[:search].nil? ? 18 : params[:search][:age_min]) , :class=> 'form-control'%>
        </div>
        <div class="col-md-6">
        To
         <%= select_tag 'search[age_max]' , options_for_select((14..100), params[:search].nil? ? 28 : params[:search][:age_max]) , :class=> 'form-control'%>
        </div>
      </div>
    </div>

    <div class="innerAll text-center">
      <button class="btn btn-block btn-success">Search <i class="fa fa-fw fa-search"></i></button>
    </div>
  </div>
</div>

<!-- // END col-separator -->


</div>
<% end %>

app/views/profiles/index/_profile.html.erb
<div class="col-sm-6">
  <div class="bg-white innerAll" data-animate="bounceIn" data-delay="200">
    <div class="media margin-none">
      <a href="<%= profile_path(username: user.username) %>" class="pull-left" style="width: 200px;">
        <%= image_medium user.avatar, ' class="img-responsive" ' %>
      </a>
      <div class="media-body">
        <div class="pull-right">
          <a href="realestate_listing_list.html?lang=en" class="btn btn-default btn-xs"><i class="fa fa-info fa-fw"></i></a>
          <a href="realestate_listing_list.html?lang=en" class="btn btn-primary btn-xs"><i class="fa fa-shopping-cart fa-fw"></i></a>
        </div>

        <h3 class="margin-none"><%= link_to user.username, profile_path(username: user.username) %></h3>

        <div class="innerAll bg-gray">
          <span class="text-primary strong"><%= user.age %></span>
          &nbsp;
          <span class="label label-default"><%= t user.sex_text %></span>
          &nbsp;
          <i class="fa fa-fw fa-map-marker"></i> <%= user.city.name %>
        </div>
        <div class="separator"></div>
        <div class="row">
          <div class="col-md-4">Height</div>
          <div class="col-md-8"><span class="strong"><%= user.height %></span> cm.</div>
        </div>
        <div class="row">
          <div class="col-md-4">Weight</div>
          <div class="col-md-8"><span class="strong"><%= user.weight %></span> kg.</div>
        </div>
        <div class="row">
          <div class="col-md-4">Eye color</div>
          <div class="col-md-8"><span class="strong"><%= user.eye_color_text %></span></div>
        </div>
      </div>
    </div>
  </div>
  <div class="separator"></div>
</div>

app/views/profiles/index/_right_col.html.erb
<!-- col -->
              <div class="col-lg-8 col-md-8 col-sm-12">

                <!-- col-separator -->
                <div class="col-separator col-unscrollable col-separator-last bg-none">

                  <!-- col-table -->
                  <div class="col-table">

                    <div class="innerAll bg-white">
                      <h4 class="margin-none innerT half pull-left"><%= t 'Users' %></h4>
                      <div class="btn-group btn-group-sm pull-right">
                        <a href="realestate_listing_grid.html?lang=en" class="btn btn-default"><i class="fa fa-th"></i></a>
                        <a href="realestate_listing_list.html?lang=en" class="btn btn-primary"><i class="fa fa-list"></i></a>
                      </div>
                      <div class="clearfix"></div>
                    </div>

                    <div class="col-separator-h"></div>

                    <!-- col-table-row -->
                    <div class="col-table-row">

                      <!-- col-app -->
                      <div class="col-app col-unscrollable">

                        <!-- col-app -->
                        <div class="col-app">

                          <div class="innerAll2">
                          <% @profiles.each do |user| %>
                            <%= render 'profiles/index/profile', :user => user %>
                          <% end %>
                          <div class='clearfix'></div>
                          <div class="row" style='text-align:center'>
                          <%= will_paginate @profiles, renderer: BootstrapPagination::Rails  %></div>

                            </div>
                          </div>

                        </div>
                        <!-- // END col-app -->

                      </div>
                      <!-- // END col-app -->

                    </div>
                    <!-- // END col-table-row -->

                  </div>
                  <!-- // END col-table -->

                </div>
                <!-- // END col-separator -->